version: 2
before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
      - -ldflags
      - '-s -w'
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    binary: irsa-webhook

archives:
  - formats: zip
    files:
      - none*
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS'
  algorithm: sha256

dockers:
  - dockerfile: Dockerfile.goreleaser
    image_templates:
      - "vultr/irsa-webhook:release"
      - "vultr/irsa-webhook:latest"
      - "vultr/irsa-webhook:{{ .Tag }}"

release:
  draft: false