apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-irsa
  namespace: default
  annotations:
    api.vultr.com/role: "775a6be6-45cd-4f19-94f5-6e4f96f093ec"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  serviceAccountName: test-irsa
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "env | grep AWS && ls -la /var/run/secrets/vultr.com/serviceaccount/ && sleep 3600"]
